-- updatedAt 字段时区修复脚本
-- 移除 Prisma @updatedAt，改用 MySQL ON UPDATE CURRENT_TIMESTAMP
-- 这样 MySQL 直接用 CURRENT_TIMESTAMP（北京时间）更新 updatedAt，绕过 Prisma 的 UTC 序列化
-- 执行前请先备份数据库！

-- 注意：此脚本必须在 prisma db push 之后执行
-- prisma db push 会设置 DEFAULT CURRENT_TIMESTAMP，但不会设置 ON UPDATE CURRENT_TIMESTAMP

ALTER TABLE users MODIFY COLUMN updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE order_takers MODIFY COLUMN updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE tasks MODIFY COLUMN updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE orders MODIFY COLUMN updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE system_settings MODIFY COLUMN updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE repeat_discounts MODIFY COLUMN updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE repeat_discount_analyses MODIFY COLUMN updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- 验证：检查 ON UPDATE CURRENT_TIMESTAMP 是否生效
SELECT TABLE_NAME, COLUMN_NAME, COLUMN_DEFAULT, EXTRA 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_SCHEMA = 'tmall_incentive' 
AND COLUMN_NAME = 'updatedAt';
